workflows:
  my-workflow:
    name: Suresh FLow
    labels:
      - QA
      - ${SUresh}
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - flutter
      vars:
        PUBLIC_ENV_VAR: "a"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/pubspec.yaml
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - rkrish26081994@gmail.com
      scripts:
        - echo 'Post-publish script'
