workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    
  ios-workflow:
      name: iOS Workflow
      instance_type: mac_mini_m1
      environment:
        xcode: 13.4.1
   artifacts:
        - "**/ios_tests.zip"      
  
